## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=5G
#$ -l tmp_requested=5G
#$ -N extract_snps

cd $SGE_O_WORKDIR
BIN=$SGE_O_WORKDIR/../bin

awk '{if(($5 ~ /A|G|C|T/) && $6 ~ (/A|G|C|T/)){print}}' ../data/OneK1K_Genotype_hg38_corrected_ids_remdup.bim | cut -f2 > extract_snps.txt
INPUT=../data/OneK1K_Genotype_hg38_corrected_ids_remdup
OUTPUT=extract_snps
mkdir $OUTPUT
${BIN}/plink --bfile ${INPUT} --extract extract_snps.txt --make-bed --out ${OUTPUT}/${OUTPUT} --noweb
mv extract_snps.txt ${OUTPUT}
