## SGE SETTINGS
#$ -cwd
#$ -S /bin/bash
#$ -q short.q
#$ -r yes
#$ -l mem_requested=5G
#$ -l tmp_requested=5G
#$ -N maf

cd $SGE_O_WORKDIR
BIN=$SGE_O_WORKDIR/../bin
export PATH=$PATH:$BIN

INPUT=update_sex/update_sex
OUTPUT=maf
MAF=0.01
mkdir $OUTPUT
plink --bfile ${INPUT} --freq --out ${OUTPUT}/freq --noweb
plink2 --bfile ${INPUT} --maf ${MAF}  --allow-extra-chr --make-bed  --out ${OUTPUT}/${OUTPUT}

printf "s/X/23/\ns/Y/24/\ns/MT/26/\n" > ${OUTPUT}/chr_coding
paste <(sed -f ${OUTPUT}/chr_coding <(cut -f1 ${OUTPUT}/${OUTPUT}.bim)) <(cut -f2- ${OUTPUT}/${OUTPUT}.bim) > ${OUTPUT}/${OUTPUT}_tmp.bim
mv ${OUTPUT}/${OUTPUT}.bim ${OUTPUT}/${OUTPUT}_plink2.bim
mv ${OUTPUT}/${OUTPUT}_tmp.bim ${OUTPUT}/${OUTPUT}.bim
